
Traceback (most recent call last):

  File "tests/exceptions/backtrace/chained_expression_direct.py", line 11, in a_decorated
    1 / 0

ZeroDivisionError: division by zero


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "tests/exceptions/backtrace/chained_expression_direct.py", line 39, in <module>
    b_decorator()
    └ <function b_decorator at 0xDEADBEEF>

> File "tests/exceptions/backtrace/chained_expression_direct.py", line 24, in b_decorator
    a_decorated()
    └ <function a_decorated at 0xDEADBEEF>

  File "tests/exceptions/backtrace/chained_expression_direct.py", line 13, in a_decorated
    raise ValueError("NOK")
          └ <class 'ValueError'>

ValueError: NOK

Traceback (most recent call last):

  File "tests/exceptions/backtrace/chained_expression_direct.py", line 18, in a_not_decorated
    1 / 0

ZeroDivisionError: division by zero


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "tests/exceptions/backtrace/chained_expression_direct.py", line 40, in <module>
    b_context_manager()
    └ <function b_context_manager at 0xDEADBEEF>

> File "tests/exceptions/backtrace/chained_expression_direct.py", line 29, in b_context_manager
    a_not_decorated()
    └ <function a_not_decorated at 0xDEADBEEF>

  File "tests/exceptions/backtrace/chained_expression_direct.py", line 20, in a_not_decorated
    raise ValueError("NOK")
          └ <class 'ValueError'>

ValueError: NOK

Traceback (most recent call last):

  File "tests/exceptions/backtrace/chained_expression_direct.py", line 18, in a_not_decorated
    1 / 0

ZeroDivisionError: division by zero


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "tests/exceptions/backtrace/chained_expression_direct.py", line 41, in <module>
    b_explicit()
    └ <function b_explicit at 0xDEADBEEF>

> File "tests/exceptions/backtrace/chained_expression_direct.py", line 34, in b_explicit
    a_not_decorated()
    └ <function a_not_decorated at 0xDEADBEEF>

  File "tests/exceptions/backtrace/chained_expression_direct.py", line 20, in a_not_decorated
    raise ValueError("NOK")
          └ <class 'ValueError'>

ValueError: NOK
