
Traceback (most recent call last):
  File "tests/exceptions/backtrace/chaining_third.py", line 45, in <module>
    a_decorator()
  File "tests/exceptions/backtrace/chaining_third.py", line 9, in a_decorator
    b_decorator()
> File "tests/exceptions/backtrace/chaining_third.py", line 21, in b_decorator
    c_decorated()
  File "tests/exceptions/backtrace/chaining_third.py", line 38, in c_decorated
    1 / 0
ZeroDivisionError: division by zero

Traceback (most recent call last):
  File "tests/exceptions/backtrace/chaining_third.py", line 46, in <module>
    a_context_manager()
  File "tests/exceptions/backtrace/chaining_third.py", line 13, in a_context_manager
    b_context_manager()
> File "tests/exceptions/backtrace/chaining_third.py", line 26, in b_context_manager
    c_not_decorated()
  File "tests/exceptions/backtrace/chaining_third.py", line 42, in c_not_decorated
    1 / 0
ZeroDivisionError: division by zero

Traceback (most recent call last):
  File "tests/exceptions/backtrace/chaining_third.py", line 47, in <module>
    a_explicit()
  File "tests/exceptions/backtrace/chaining_third.py", line 17, in a_explicit
    b_explicit()
> File "tests/exceptions/backtrace/chaining_third.py", line 31, in b_explicit
    c_not_decorated()
  File "tests/exceptions/backtrace/chaining_third.py", line 42, in c_not_decorated
    1 / 0
ZeroDivisionError: division by zero
