
Traceback (most recent call last):

> File "tests/exceptions/backtrace/function.py", line 21, in <module>
    a()
    └ <function a at 0xDEADBEEF>

  File "tests/exceptions/backtrace/function.py", line 10, in a
    1 / 0

ZeroDivisionError: division by zero

Traceback (most recent call last):

> File "tests/exceptions/backtrace/function.py", line 24, in <module>
    b()
    └ <function b at 0xDEADBEEF>

  File "tests/exceptions/backtrace/function.py", line 14, in b
    2 / 0

ZeroDivisionError: division by zero

Traceback (most recent call last):

> File "tests/exceptions/backtrace/function.py", line 27, in <module>
    c()
    └ <function c at 0xDEADBEEF>

  File "tests/exceptions/backtrace/function.py", line 18, in c
    3 / 0

ZeroDivisionError: division by zero
