
Traceback (most recent call last):
  File "tests/exceptions/backtrace/nested.py", line 16, in <module>
    a(0)
> File "tests/exceptions/backtrace/nested.py", line 13, in a
    nested(x)
  File "tests/exceptions/backtrace/nested.py", line 11, in nested
    1 / i
ZeroDivisionError: division by zero

Traceback (most recent call last):
  File "tests/exceptions/backtrace/nested.py", line 27, in <module>
    b(0)
> File "tests/exceptions/backtrace/nested.py", line 24, in b
    nested(x)
  File "tests/exceptions/backtrace/nested.py", line 21, in nested
    1 / i
ZeroDivisionError: division by zero

Traceback (most recent call last):
  File "tests/exceptions/backtrace/nested.py", line 40, in <module>
    c(0)
> File "tests/exceptions/backtrace/nested.py", line 35, in c
    nested(x)
  File "tests/exceptions/backtrace/nested.py", line 32, in nested
    1 / i
ZeroDivisionError: division by zero
