
Traceback (most recent call last):
  File "tests/exceptions/backtrace/suppressed_expression_indirect.py", line 14, in b
    a(1, 0)
  File "tests/exceptions/backtrace/suppressed_expression_indirect.py", line 9, in a
    x / y
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
> File "tests/exceptions/backtrace/suppressed_expression_indirect.py", line 28, in <module>
    c_decorated()
  File "tests/exceptions/backtrace/suppressed_expression_indirect.py", line 21, in c_decorated
    b()
  File "tests/exceptions/backtrace/suppressed_expression_indirect.py", line 16, in b
    raise ValueError("NOK") from e
ValueError: NOK

Traceback (most recent call last):
  File "tests/exceptions/backtrace/suppressed_expression_indirect.py", line 14, in b
    a(1, 0)
  File "tests/exceptions/backtrace/suppressed_expression_indirect.py", line 9, in a
    x / y
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
> File "tests/exceptions/backtrace/suppressed_expression_indirect.py", line 31, in <module>
    c_not_decorated()
  File "tests/exceptions/backtrace/suppressed_expression_indirect.py", line 25, in c_not_decorated
    b()
  File "tests/exceptions/backtrace/suppressed_expression_indirect.py", line 16, in b
    raise ValueError("NOK") from e
ValueError: NOK

Traceback (most recent call last):
  File "tests/exceptions/backtrace/suppressed_expression_indirect.py", line 14, in b
    a(1, 0)
  File "tests/exceptions/backtrace/suppressed_expression_indirect.py", line 9, in a
    x / y
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
> File "tests/exceptions/backtrace/suppressed_expression_indirect.py", line 34, in <module>
    c_not_decorated()
  File "tests/exceptions/backtrace/suppressed_expression_indirect.py", line 25, in c_not_decorated
    b()
  File "tests/exceptions/backtrace/suppressed_expression_indirect.py", line 16, in b
    raise ValueError("NOK") from e
ValueError: NOK
