
[33m[1mTraceback (most recent call last):[m

  File "[32mtests/exceptions/diagnose/[m[32m[1msource_strings.py[m", line [33m11[m, in [35m<module>[m
    [38;5;231ma[0m [38;5;197m+[0m [38;5;222mb"prefix"[0m [38;5;197m+[0m [38;5;222m'single'[0m [38;5;197m+[0m [38;5;222m"""triple"""[0m [38;5;197m+[0m [38;5;141m1[0m [38;5;197m+[0m [38;5;231mb[0m
    [36mâ”‚                                             â”” [m[36m[1m0[m
    [36mâ”” [m[36m[1m0[m

[31m[1mTypeError[m:[1m unsupported operand type(s) for +: 'int' and 'bytes'[m
