
Traceback (most recent call last):

  File "tests/exceptions/source/others/exception_in_property.py", line 22, in <module>
    value = a.value
            │ └ <property object at 0xDEADBEEF>
            └ <__main__.A object at 0xDEADBEEF>

> File "tests/exceptions/source/others/exception_in_property.py", line 13, in value
    1 / 0

ZeroDivisionError: division by zero
